title: Brian Arcelo # your name (or website title) here
logo: <img src="images/4-4-19-edit.jpg"> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a senior high school fresh graduate looking for employment in a job that will allow me to experience the transition from a school life to adulthood in the real world and most importantly provide me with independent financial stability.
  <br><br>
  My financial status prevents me from affording college. To make up for it, I am self-studying web-development languages like HTML, CSS, and Javascript. Soon, I will also teach myself programming languages; currently interested in Java, C++, and Python.
  <br><br>
  
theme: jekyll-theme-midnight
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
